### ISSUE TITLE
JMeterThread: Error while processing sampler: 'GrpcRequest'

### ISSUE THREAD

**Issue by BesSlaaneshi** [zalopay-oss/jmeter-grpc-request#1]
Running on: Windows 10 Enterprise
Jmeter version 5.3

FULL_METHOD: grpc.marketdata.MDRequest.GetQuotes
Folder structure:
```
packages
    grpc
        marketdata
            MDRequest.proto
            tagget_security.proto
    proto
        marketdata
            marketdata.proto
```
i set PROTO_FOLDER as path to packages

MDRequest.proto looks like (i hid lines that are not important): 
syntax = "proto3";

package grpc.marketdata;

import "google/rpc/status.proto";
import "google/protobuf/field_mask.proto";
import "proto/marketdata/marketdata.proto";
import "grpc/marketdata/tagged_security.proto";

service MDRequest {
	rpc GetQuotes(QuotesRequest) returns (QuotesResponse) {}
}

my REQUEST_FILE:
{
	"securities":[
			{"id": {"security_id": "123456"},"tag":"123456"},		
		]
	}
TLS: false
DEADLINE: 20000

errors i get:
```
2020-05-28 18:09:26,298 INFO o.j.r.PluginManager: Plugins Status: [jpgc-plugins-manager=1.4, jmeter-core=5.3, jmeter-ftp=5.3, jmeter-http=5.3, jmeter-jdbc=5.3, jmeter-jms=5.3, jmeter-junit=5.3, jmeter-java=5.3, jmeter-ldap=5.3, jmeter-mail=5.3, jmeter-mongodb=5.3, jmeter-native=5.3, jmeter-tcp=5.3, jmeter-components=5.3]
2020-05-28 18:09:27,254 WARN o.a.j.t.BeanInfoSupport: Localized strings not available for bean class vn.zalopay.benchmark.testbean.GrpcRequest
java.util.MissingResourceException: Can't find bundle for base name vn.zalopay.benchmark.testbean.GrpcRequestResources, locale en_EN
	at java.util.ResourceBundle.throwMissingResourceException(Unknown Source) ~[?:1.8.0_241]
	at java.util.ResourceBundle.getBundleImpl(Unknown Source) ~[?:1.8.0_241]
	at java.util.ResourceBundle.getBundle(Unknown Source) ~[?:1.8.0_241]
	at org.apache.jmeter.testbeans.BeanInfoSupport.<init>(BeanInfoSupport.java:126) ~[ApacheJMeter_core.jar:5.3]
	at vn.zalopay.benchmark.testbean.GrpcRequestBeanInfo.<init>(GrpcRequestBeanInfo.java:17) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at com.sun.beans.finder.InstanceFinder.instantiate(Unknown Source) ~[?:1.8.0_241]
	at com.sun.beans.finder.InstanceFinder.find(Unknown Source) ~[?:1.8.0_241]
	at java.beans.Introspector.findExplicitBeanInfo(Unknown Source) ~[?:1.8.0_241]
	at java.beans.Introspector.<init>(Unknown Source) ~[?:1.8.0_241]
	at java.beans.Introspector.getBeanInfo(Unknown Source) ~[?:1.8.0_241]
	at org.apache.jmeter.testbeans.gui.TestBeanGUI.<init>(TestBeanGUI.java:164) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.getGUIComponent(MenuFactory.java:202) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:151) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:107) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:94) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:184) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_241]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_241]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_241]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_241]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_241]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_241]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_241]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_241]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_241]
2020-05-28 18:14:22,615 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-05-28 18:14:22,615 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-05-28 18:14:22,615 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-05-28 18:14:22,615 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2020-05-28 18:14:22,615 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2020-05-28 18:14:22,865 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-05-28 18:14:23,036 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-05-28 18:14:23,036 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-05-28 18:14:23,036 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-05-28 18:14:23,036 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-05-28 18:14:23,036 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-05-28 18:14:23,036 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-05-28 18:14:23,052 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-05-28 18:14:23,052 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GrpcRequest'.
java.lang.IllegalArgumentException: Could not extract full service from grpc.marketdata.MDRequest.GetQuotes
	at vn.zalopay.benchmark.core.protobuf.ProtoMethodName.parseFullGrpcMethodName(ProtoMethodName.java:17) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:36) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:30) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.init(GrpcRequest.java:28) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.sample(GrpcRequest.java:34) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by BesSlaaneshi** [comment]
also: 
call grpc.marketdata.MDRequest.GetQuotes works fine in GHZ (load testing util for grpc)

**Comment by huynhminhtan** [comment]
Hi @BesSlaaneshi,

Welcome to zalopay-oss / jmeter-grpc-request

Please check the FULL_METHOD: `grpc.marketdata.MDRequest/GetQuotes` not `grpc.marketdata.MDRequest.GetQuotes`. FULL_METHOD is structured as: `<package>. <service>/<method>`.

Please check again, if there's an error again let me know. I hope to see your good news.

**Comment by BesSlaaneshi** [comment]
oh thank you, it helped with that error, but i still have problem, now with import proto

jmeter console:
May 29, 2020 12:59:44 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=1, target=10.77.192.246:5666} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
        at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannel(ChannelFactory.java:24)
        at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:41)
        at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:30)
        at vn.zalopay.benchmark.testbean.GrpcRequest.init(GrpcRequest.java:28)
        at vn.zalopay.benchmark.testbean.GrpcRequest.sample(GrpcRequest.java:34)
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
        at java.lang.Thread.run(Unknown Source)

google/rpc/status.proto: File not found.
google/type/date.proto: File not found.
proto/common/types.proto: File not found.
proto/marketdata/marketdata.proto:8:1: Import "google/type/date.proto" was not found or had errors.
proto/marketdata/marketdata.proto:10:1: Import "proto/common/types.proto" was not found or had errors.
proto/marketdata/marketdata.proto:92:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:93:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:94:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:95:9: "google.type.Date" is not defined.
proto/marketdata/marketdata.proto:99:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:100:9: "google.type.Date" is not defined.
proto/marketdata/marketdata.proto:107:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:108:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:109:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:110:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:152:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:153:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:158:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:165:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:166:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:167:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:168:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:169:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:170:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:171:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:172:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:173:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:174:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:175:13: "google.type.Date" is not defined.
proto/marketdata/marketdata.proto:46:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:48:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:49:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:51:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:54:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:55:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:56:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:57:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:58:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:62:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:64:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:65:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:67:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:70:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:71:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:72:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:73:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:74:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:77:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:78:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:80:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:81:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:84:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:85:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:87:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:88:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:128:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:129:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:130:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:133:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:134:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:135:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:138:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:139:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:140:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:143:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:144:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:145:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:146:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:211:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:214:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:221:5: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:239:9: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:241:13: "proto.common.Decimal" is not defined.
proto/marketdata/marketdata.proto:242:13: "proto.common.Decimal" is not defined.
proto/common/securityidentifier.proto: File not found.
grpc/marketdata/quotes.proto:5:1: Import "google/rpc/status.proto" was not found or had errors.
grpc/marketdata/quotes.proto:7:1: Import "proto/marketdata/marketdata.proto" was not found or had errors.
grpc/marketdata/quotes.proto:8:1: Import "proto/common/securityidentifier.proto" was not found or had errors.
grpc/marketdata/quotes.proto:25:5: "google.rpc.Status" is not defined.
grpc/marketdata/quotes.proto:26:5: "proto.marketdata.Quote" is not defined.
grpc/marketdata/quotes.proto:32:14: "proto.common.SecurityIdentifier" is not defined.
grpc/marketdata/quotes.proto:45:9: "google.rpc.Status" is not defined.
grpc/marketdata/quotes.proto:46:9: "proto.common.SecurityIdentifier" is not defined.
grpc/marketdata/quotes.proto:47:9: "proto.marketdata.Quote" is not defined.

[full log.txt](https://github.com/zalopay-oss/jmeter-grpc-request/files/4701062/full.log.txt)

i think that the problem is in that we have many proto files for servers
but they compile with protoc without errors. (and using and working with our servers pretty well)
only jmeter return errors :(

Also, can you provide support for protoset files? (.pb)

**Comment by huynhminhtan** [comment]
Hi @BesSlaaneshi,

*Jmeter-grpc-request* works great when importing from other proto files, but currently doesn't support importing from external packages like Google APIs (you're using `google/rpc/status.proto`, `google/protobuf/field_mask.proto`, ...).

I am doing an upgrade by adding a protoc binary to solve it, thanks for your issue.

**Comment by anhldbk** [comment]
Close this issue due to inactivity. @BesSlaaneshi feel free to re-open.

**Comment by BesSlaaneshi** [comment]
Oh, why close?
i though that @huynhminhtan will upgrade by adding a protoc binary to solve this problem

**Comment by BesSlaaneshi** [comment]
@anhldbk i cant re-open this issue because it wasn't closed by me

**Comment by huynhminhtan** [comment]
Hi @BesSlaaneshi Be,

Please check out the [binlib](https://github.com/zalopay-oss/jmeter-grpc-request/tree/binlib) branch to make requests with external packages like Google APIs (you're using google / rpc / status.proto, google / protobuf / field_mask.proto, ...). I am preparing to merge to master (to have a stable version).

To use:
	- Download JMeter at [apache-jmeter-5.1.1.zip](https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.1.1.zip), unzip and then copy [jmeter-grpc-request-1.1.0-SNAPSHOT.jar](https://github.com/zalopay-oss/jmeter-grpc-request/blob/binlib/dist/bin/jmeter-grpc-request-1.1.0-SNAPSHOT.jar) to the `lib/ext` directory of JMeter and restart JMeter.
	- You can see an example at [SegmentService_checkSeg_metadata.jmx](https://github.com/zalopay-oss/jmeter-grpc-request/blob/binlib/dist/benchmark/SegmentService_checkSeg_metadata.jmx).

The screenshot, with LIB_FOLDER (for example, I use [googleapis/googleapis](https://github.com/googleapis/googleapis) in my proto):

![image](https://user-images.githubusercontent.com/15891411/89522688-d5b6fa80-d80b-11ea-81f2-426efdfe5bd2.png)

If you have any questions please don't hesitate to contact me.
Regards.

**Comment by BesSlaaneshi** [comment]
Hello, i'm not sure that it's the same problem, and i'm not sure that i done all correctly, but i have errors in protoc.
Maybe i did something wrong?
![изображение](https://user-images.githubusercontent.com/40031332/90670555-0bbc9b80-e25c-11ea-9d7a-498cfc3b4153.png)
jmeter verrsion 5.1.1 and  jmeter-grpc-request-1.1.0-SNAPSHOT.jar and protoc-3.10.1
(but we compile this proto files same way with protoc and they compiles)

2020-08-19 20:35:26,747 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-08-19 20:35:26,747 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-08-19 20:35:26,762 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-08-19 20:35:26,816 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-08-19 20:35:26,816 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-08-19 20:35:26,816 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-08-19 20:35:26,816 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-08-19 20:35:26,816 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-08-19 20:35:26,816 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-08-19 20:35:26,816 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-08-19 20:35:27,217 WARN v.z.b.c.p.ProtocInvoker: Protoc invocation failed with status: 1
2020-08-19 20:35:27,217 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: protoc version: 3.10.1, detected platform: windows-x86_64 (windows 10/amd64)

2020-08-19 20:35:27,217 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: embedded: bin/3.10.1/protoc-3.10.1-windows-x86_64.exe

2020-08-19 20:35:27,217 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: executing: [C:\Users\me\AppData\Local\Temp\protocjar1333349057598853925\bin\protoc.exe, C:\proto-repo\grpc-reference\src\main\proto\grpc\reference\instrumentlist.proto, C:\proto-repo\grpc-reference\src\main\proto\proto\reference\security.proto, C:\proto-repo\grpc-reference\src\main\proto\grpc\reference\securityreference.proto, -IC:\apache-jmeter-5.1.1\bin, -IC:\Users\me\AppData\Local\Temp\polyglot-well-known-types6948052827182340520, -IC:\proto-repo\grpc-reference\src\main\proto, --descriptor_set_out=C:\Users\me\AppData\Local\Temp\descriptor5367171319417383293.pb.bin, --include_imports]

2020-08-19 20:35:27,217 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GrpcRequest'.
java.lang.RuntimeException: Unable to resolve service by invoking protoc
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:54) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:34) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.init(GrpcRequest.java:28) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.sample(GrpcRequest.java:34) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: vn.zalopay.benchmark.core.protobuf.ProtocInvoker$ProtocInvocationException: Got exit code [1] from protoc with args [[C:\proto-repo\grpc-reference\src\main\proto\grpc\reference\instrumentlist.proto, C:\proto-repo\grpc-reference\src\main\proto\proto\reference\security.proto, C:\proto-repo\grpc-reference\src\main\proto\grpc\reference\securityreference.proto, -IC:\apache-jmeter-5.1.1\bin, -IC:\Users\me\AppData\Local\Temp\polyglot-well-known-types6948052827182340520, -IC:\proto-repo\grpc-reference\src\main\proto, --descriptor_set_out=C:\Users\me\AppData\Local\Temp\descriptor5367171319417383293.pb.bin, --include_imports]]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:159) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:104) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:52) ~[jmeter-grpc-request-1.1.0-SNAPSHOT.jar:?]
	... 8 more
2020-08-19 20:35:27,217 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2020-08-19 20:35:27,217 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-08-19 20:35:27,217 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-08-19 20:35:27,217 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by Karthicsrv** [comment]
Hi @huynhminhtan 

is these changes merged with the master? pls share and share the github path for the external protos

Thanks in advance

**Comment by PriyaPriy** [comment]
Hi @huynhminhtan 

Same kind of the Field Mask setup have to perform in my project it will great if you share the merged master path or particular java changes.
One more update required,
if any failure happened in the gRPC current sampler then the failure count is not counted in the Aggregated Report. if you incorporate the changes along with jar. really it be useful for all the people.

Thanks in advance.

Eagerly  waiting for the updates

Regards,
Priya

**Comment by qaautomated** [comment]
@huynhminhtan I am using proto file written go .is it compatible with plugin. I am getting this error

2022-02-28 13:54:35,590 WARN v.z.b.c.p.ProtocInvoker: Protoc invocation failed with status: 1
2022-02-28 13:54:35,591 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: protoc version: 3.11.4, detected platform: windows-x86_32 (windows 10/x86)

2022-02-28 13:54:35,591 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: using default maven settings, didn't find user settings.xml

2022-02-28 13:54:35,591 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: cached: C:\Users\manojjai\AppData\Local\Temp\protocjar.webcache\com\google\protobuf\protoc\maven-metadata.xml

2022-02-28 13:54:35,591 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: cached: C:\Users\manojjai\AppData\Local\Temp\protocjar.webcache\com\google\protobuf\protoc\3.11.4\protoc-3.11.4-windows-x86_32.exe
