### ISSUE TITLE
GRPC request: Unable to use ${} as a path for Proto Root and Library Directory directories.

### ISSUE THREAD

**Issue by ASDRecords** [zalopay-oss/jmeter-grpc-request#101]
I am truing to use dynamic variable generated by BeanShell and use it as path to Proto Root and Library Directory directories.
BeanShell  that get *.jmx file path = ${__BeanShell(import org.apache.jmeter.services.FileServer; FileServer.getFileServer().getBaseDir();)}
The variable is defined in a "User Defined Variables" section and used in GRPC request.
Clicking "Listen" button at Full Method, we got the error
JMeter version: 5.4.1 
GRPC version: 1.2.1
OS: Win 10(x64)
![image](https://user-images.githubusercontent.com/78590122/151957903-750b4e07-865f-47c7-b3f2-2267622c18f3.png)
![image](https://user-images.githubusercontent.com/78590122/151958022-635ca808-73cb-4dca-b2dd-ad957cad9a79.png)

Uncaught Exception java.lang.RuntimeException: Unable to resolve service by invoking protoc in thread Thread[AWT-EventQueue-0,6,main]. See log file for details.
ERROR | Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.RuntimeException: Unable to resolve service by invoking protoc
        at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:51)
        at vn.zalopay.benchmark.GRPCSamplerGui.getMethods(GRPCSamplerGui.java:315)
        at vn.zalopay.benchmark.GRPCSamplerGui.access$100(GRPCSamplerGui.java:40)
        at vn.zalopay.benchmark.GRPCSamplerGui$1.actionPerformed(GRPCSamplerGui.java:276)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: vn.zalopay.benchmark.core.protobuf.ProtocInvoker$ProtocInvocationException: Unable to scan proto tree for files
        at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.scanProtoFiles(ProtocInvoker.java:188)
        at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:89)
        at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:44)
        ... 38 more
Caused by: java.nio.file.NoSuchFileException: C:\Users\vdiaconu\WORK\performanceframework\JMeter\src\test\jmeter\${__BeanShell(import org.apache.jmeter.services.FileServer; FileServer.getFileServer().getBaseDir();)}\ProtoFiles\PricingEngine
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.walk(Files.java:3918)
        at java.base/java.nio.file.Files.walk(Files.java:3973)
        at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.scanProtoFiles(ProtocInvoker.java:182)
        ... 40 more
Uncaught Exception java.lang.RuntimeException: Unable to resolve service by invoking protoc in thread Thread[AWT-EventQueue-0,6,main]. See log file for details.

**Comment by yl-yue** [comment]
> 貌似只能使用一个`${}`变量

It seems that only one '${}' variable can be used

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
