### ISSUE TITLE
Get error java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHost()Ljava/lang/String;

### ISSUE THREAD

**Issue by AlexBenyuh** [zalopay-oss/jmeter-grpc-request#104]
Good day
Get the error with jmeter-grpc-request-v1.2.1 plugin

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

Mac os 12.2 Apple M1
```
2022-02-14 13:20:20,058 INFO o.a.j.t.JMeterThread: Thread finished: [PROD] /v1/connections/uids 1-1
2022-02-14 13:20:20,065 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[[PROD] /v1/connections/uids 1-1,6,main]
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHost()Ljava/lang/String;
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createSSLMessageChannel(ChannelFactory.java:50) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:45) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannel(ChannelFactory.java:33) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.createDynamicClient(ClientCaller.java:122) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:73) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:46) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.initGrpcClient(GRPCSampler.java:56) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:65) ~[jmeter-grpc-request-jar-with-dependencies.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) ~[ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
2022-02-14 13:20:20,076 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test


```
![image](https://user-images.githubusercontent.com/29822662/153856543-b00ffe67-94ef-452c-ba92-5f85d3df8328.png)

**Comment by yl-yue** [comment]
> 错误的使用JMeter用户自定义变量，请使用`${}`

Incorrect use of JMeter user - defined variables, use '${}'
