### ISSUE TITLE
this.clientCaller is null

### ISSUE THREAD

**Issue by BStenfors9119** [zalopay-oss/jmeter-grpc-request#11]
I am trying to do a basic GRPC call to a local grpc service but I keep getting the following error:

`2020-10-01 09:29:44,043 ERROR o.a.j.t.JMeterThread: Error calling threadStarted
java.lang.RuntimeException: Unable to resolve service by invoking protoc
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:54) ~[jmeter-grpc-request-1.1.0.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:32) ~[jmeter-grpc-request-1.1.0.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.init(GRPCSampler.java:61) ~[jmeter-grpc-request-1.1.0.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.threadStarted(GRPCSampler.java:104) ~[jmeter-grpc-request-1.1.0.jar:?]
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:769) [ApacheJMeter_core.jar:5.3]
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:993) [jorphan.jar:5.3]
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:976) [jorphan.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:737) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:725) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:252) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: vn.zalopay.benchmark.core.protobuf.ProtocInvoker$ProtocInvocationException: Got exit code [1] from protoc with args [[/Users/bstenfors/dev/go/src/github.mitekcloud.local/engineering/cfd-platform/frauddetection/proto/frauddetection.proto, -I/Users/bstenfors/Downloads, -I/var/folders/rb/sh4ndhd56n7c71zj_0y4s2dcs0021h/T/polyglot-well-known-types4922993313676731235, -I/Users/bstenfors/dev/go/src/github.mitekcloud.local/engineering/cfd-platform/frauddetection/proto, --descriptor_set_out=/var/folders/rb/sh4ndhd56n7c71zj_0y4s2dcs0021h/T/descriptor12160106733389582436.pb.bin, --include_imports]]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:159) ~[jmeter-grpc-request-1.1.0.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:104) ~[jmeter-grpc-request-1.1.0.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:52) ~[jmeter-grpc-request-1.1.0.jar:?]
	... 10 more
2020-10-01 09:29:44,043 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GRPC Request'.
java.lang.NullPointerException: Cannot invoke "vn.zalopay.benchmark.core.ClientCaller.buildRequest(String)" because "this.clientCaller" is null
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:69) ~[jmeter-grpc-request-1.1.0.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]`

**Comment by BStenfors9119** [comment]
Please disregard original issue. I needed to fill in the Library Directory.

But now I am now getting a "NoSuchMethodError".

Any ideas?

I am trying to connect and test a GoLang GRPC Service Method.

Thanks.

**Comment by BStenfors9119** [comment]
Another ID-10-T error the NoSuchMethodError was because I still had a request using the old library.
