### ISSUE TITLE
Plugin is unusable at the moment - unable to import proto files and methods are not getting listed

### ISSUE THREAD

**Issue by rahulraj90** [zalopay-oss/jmeter-grpc-request#114]
Here is the screenshot:
<img width="1165" alt="Screenshot 2022-04-29 at 12 28 42 PM" src="https://user-images.githubusercontent.com/100914958/165898415-e3d2782b-29d8-4e90-a64f-0a21cebb1bda.png">

When I click on the listing button, nothing is happening. methods are not getting listed. 

in the jmeter console, I have these error traces:
```
2022-04-29 12:46:14,691 ERROR v.z.b.GRPCSamplerGui: request mock error
java.lang.IllegalArgumentException: Could not extract full service from 
	at vn.zalopay.benchmark.core.protobuf.ProtoMethodName.parseFullGrpcMethodName(ProtoMethodName.java:21) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.requestMock(GRPCSamplerGui.java:338) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.access$200(GRPCSamplerGui.java:40) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui$2.popupMenuWillBecomeInvisible(GRPCSamplerGui.java:286) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at javax.swing.JComboBox.firePopupMenuWillBecomeInvisible(JComboBox.java:1012) ~[?:?]
	at javax.swing.plaf.basic.BasicComboPopup.firePopupMenuWillBecomeInvisible(BasicComboPopup.java:397) ~[?:?]
	at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:809) ~[?:?]
``` 

**My protofile is very simple**:
```
syntax = "proto3";

package grpcdemo;

option java_package = "com.maersk.grpcdemo";
option java_multiple_files = true;

message HelloRequest {
  string firstName = 1;
  string lastName = 2;
}

message HelloResponse {
  string greeting = 1;
}

message SumRequest {
  int32 number = 1;
}

message SumResponse{
  int32 sum = 1;
}

message DuplexRequest{
  string itemType = 1;
}

message DuplexResponse{
  string itemName = 1;
  int32 itemPrice = 2;
  bool isAvailable = 3;
}

service HelloService {
  rpc hello(HelloRequest) returns (HelloResponse);
  rpc helloServerStreaming(HelloRequest) returns (stream HelloResponse);
  rpc helloClientStreaming(stream SumRequest) returns (SumResponse);
  rpc helloDuplex(stream DuplexRequest) returns (stream DuplexResponse);
}
```

<img width="372" alt="Screenshot 2022-04-29 at 12 53 26 PM" src="https://user-images.githubusercontent.com/100914958/165901260-ce7dd8e1-216d-46cd-b5f1-742addfce005.png">

Please help identify what's going wrong here. At the moment, this is a blocker for using this plugin.

**Comment by steverawlins-zebra** [comment]
Try with SSL selected.

**Comment by yl-yue** [comment]
Maybe this bug has been fixed, you use the latest source code to compile try
