### ISSUE TITLE
use v1.2.2 ， Error calling GRPC interface using proto.any encoded parameter

### ISSUE THREAD

**Issue by huang0227** [zalopay-oss/jmeter-grpc-request#126]
Caused by: com.google.protobuf.InvalidProtocolBufferException: Missing type url when parsing: {"url1":"type.googleapis.com/pb.Body","value":"CgdDaGlkLTAxEg9DaGFpbiBuYW1lIDAwMDEaDWNoYWluIGppZXNoYW8="}
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeAny(JsonFormat.java:1527) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.access$2000(JsonFormat.java:1295) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl$1.merge(JsonFormat.java:1366) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1455) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1999) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1663) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1500) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1458) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1340) ~[jmeter-grpc-request.jar:?]
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:476) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.message.Reader.read(Reader.java:33) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.buildRequestAndMetadata(ClientCaller.java:144) ~[jmeter-grpc-request.jar:?]
	... 6 more

**Comment by minhhoangvn** [comment]
Can you share your proto file for debugging purpose

**Comment by huang0227** [comment]
> 

syntax = "proto3";
option go_package = "../pb";
package pb;

import "google/protobuf/any.proto";

service TestService {
  rpc CreateRecord(Request) returns (Response);
}

message Request {
  google.protobuf.Any body = 1;
  AuthInfo auth_info = 2;
}

message AuthInfo {
  string nonce = 1;
  string id = 2;
  string public_key = 3;
}

message Record {
  string id = 1;
  string data = 2;
}

message Response {
  string code = 1;
  string msg = 2;
  google.protobuf.Any data = 3;
}

**Comment by huang0227** [comment]
https://blog.csdn.net/kokjuis/article/details/94548711 ,  I don't know if the contents of this website can solve this bug

**Comment by huang0227** [comment]
// This collects all known types into a registry for resolution of potential "Any" types.
            registry = JsonFormat.TypeRegistry.newBuilder()
                    .add(serviceResolver.listMessageTypes())
                    .build();

【registry】  change to T【ypeRegistry registry】， I don't know if this change can solve this bug

**Comment by huang0227** [comment]
I hope the developers can fix this as soon as possible. Thank you

**Comment by minhhoangvn** [comment]
thank @huang0227, let me see the article, however, I guess the problem is related to any data type field, and we cannot simply parse/serialize arbitrary JSON to Any (or vice versa).

**Comment by huang0227** [comment]
@minhhoangvn  Hi, thanks for your reply. Is the any you use a custom any? I am using google protobuf any（import "google/protobuf/any.proto）。 Please have a look again. Thank you
![lQLPJxZzgAL9gi3NARzNAfSwFZUMtpXCC8QCvk00I8BjAA_500_284](https://user-images.githubusercontent.com/14272473/176589056-da481ffa-20fc-4971-a61d-55d040bca5e7.png)

**Comment by minhhoangvn** [comment]
> @minhhoangvn Hi, thanks for your reply. Is the any you use a custom any? I am using google protobuf any（import "google/protobuf/any.proto）。 Please have a look again. Thank you ![lQLPJxZzgAL9gi3NARzNAfSwFZUMtpXCC8QCvk00I8BjAA_500_284](https://user-images.githubusercontent.com/14272473/176589056-da481ffa-20fc-4971-a61d-55d040bca5e7.png)

I copy the data from google/protobuf/any.proto and append it to your proto file (https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/any.proto). Currently, your performance script should have a logic to read the type in URL and use jackson-dataformat-protobuf library to convert base64 data to your type data. The JMeter plugin will be hard to support to get the URL/resource name that uniquely identifies the type of the serialized in Any type.

**Comment by huang0227** [comment]
@minhhoangvn  Thank you for your help. I see the way you said, but we are using Golang to write the code, can you solve this problem in your plug-in? thank you

**Comment by minhhoangvn** [comment]
@huang0227, I mean you can edit the proto file for JMeter can parse and run your test, and if you need to assert the data of value field in Any type you can use the jackson-dataformat-protobuf library and convert base64 gRPC data to your JSON data with RS232 element
