### ISSUE TITLE
使用插件调用gRPC接口，但是抛出异常Exception: io.grpc.StatusRuntimeException: INTERNAL: http2 exception. []

### ISSUE THREAD

**Issue by tansunyj** [zalopay-oss/jmeter-grpc-request#130]
一、环境：
    1.被测应用：https://gitee.com/whosly/study-grpc.git；
    2.插件版本：1.2.3;
二、现象：
    调用gRPC接口报告异常Exception: io.grpc.StatusRuntimeException: INTERNAL: http2 exception. []
三、排查：
    经过debug，ClientCaller类中public GrpcResponse call(String deadlineMs) 方法try代码块抛出异常；

**Comment by aisuosuo** [comment]
> 你好，你先尝试下这个包：https://github.com/yue-open/jmeter-grpc-request/releases/tag/v1.1.1 是否还有错误，或者可获得具体错误原因。

<img width="413" alt="image" src="https://user-images.githubusercontent.com/28430113/180353364-52514b16-6177-4857-8f80-eb58fdf22139.png">

**Comment by yl-yue** [comment]
你好，请截图响应异常：

![image](https://user-images.githubusercontent.com/39790401/180354383-50449021-eceb-41d6-850e-bc212c74198b.png)

**Comment by aisuosuo** [comment]
> 你好，请截图响应异常：
> 
> ![image](https://user-images.githubusercontent.com/39790401/180354383-50449021-eceb-41d6-850e-bc212c74198b.png)

下午试了一下，又好了。。。

**Comment by tansunyj** [comment]
> 你好，你先尝试下这个包：https://github.com/yue-open/jmeter-grpc-request/releases/tag/v1.1.1 是否还有错误，或者可获得具体错误原因。

使用v1.1.1版本的插件，同样的报错，错误详情是
java.lang.RuntimeException: Caught exception while parsing request for rpc
	at vn.zalopay.benchmark.core.ClientCaller.buildRequestAndMetadata(ClientCaller.java:150)
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:84)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
	at java.lang.Thread.run(null:-1)


环境：
1. idea打开压缩包中的项目，如果spring-grpc-server模块报错，可mvn package 一下spring-grpc-api模块
2. 启动项目；
3. 脚本、proto文件都在压缩包中
[greetingService.zip](https://github.com/zalopay-oss/jmeter-grpc-request/files/9172831/greetingService.zip)

**Comment by yl-yue** [comment]
@tansunyj 我担心你插件版本用错了，现主仓库已发布最新的插件：https://github.com/zalopay-oss/jmeter-grpc-request/releases/tag/v1.2.4

如果使用这个插件，你获得的异常应该类似上面的截图，你可以截取更多异常上下文信息，来帮助我们定位错误，以助问题更快的解决，因为我们在使用时，暂未遇到任何会导致不可使用的错误。

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
