### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Exception.getCause()" is null

### ISSUE THREAD

**Issue by binglien** [zalopay-oss/jmeter-grpc-request#171]
Hi...

How to fix this, thank you.

```
2022-09-13 17:40:38,179 INFO o.j.r.PluginManager: Plugins Status: [bzm-http2-legacy=2.0, bzm-http2=2.0, jmeter-grpc-request=v1.2.1, jpgc-plugins-manager=1.7, jmeter-core=5.5, jmeter-ftp=5.5, jmeter-http=5.5, jmeter-jdbc=5.5, jmeter-jms=5.5, jmeter-junit=5.5, jmeter-java=5.5, jmeter-ldap=5.5, jmeter-mail=5.5, jmeter-mongodb=5.5, jmeter-native=5.5, jmeter-tcp=5.5, jmeter-components=5.5]
2022-09-13 17:40:39,609 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2022-09-13 17:40:39,620 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2022-09-13 17:40:39,622 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2022-09-13 17:40:39,639 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2022-09-13 17:40:39,639 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2022-09-13 17:40:39,639 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2022-09-13 17:40:39,639 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2022-09-13 17:40:39,639 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2022-09-13 17:40:39,639 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2022-09-13 17:41:10,413 INFO o.a.j.s.FileServer: Default base='/Users/bing/SynologyDrive/HITRUST_DEV/tools/apache-jmeter-5.5/bin'
2022-09-13 17:41:10,416 INFO o.a.j.g.a.Load: Loading file: /Users/bing/SynologyDrive/HITRUST_DEV/tools/apache-jmeter-5.5/grpc-hsm-direct.jmx
2022-09-13 17:41:10,417 INFO o.a.j.s.FileServer: Set new base='/Users/bing/SynologyDrive/HITRUST_DEV/tools/apache-jmeter-5.5'
2022-09-13 17:41:10,417 INFO o.a.j.s.SaveService: Loading file: /Users/bing/SynologyDrive/HITRUST_DEV/tools/apache-jmeter-5.5/grpc-hsm-direct.jmx
2022-09-13 17:41:10,682 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2022-09-13 17:41:10,682 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2022-09-13 17:41:10,682 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2022-09-13 17:41:10,682 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2022-09-13 17:41:10,818 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:10,902 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:10,970 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,032 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,092 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,153 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,218 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,275 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,332 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,412 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,479 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,535 INFO o.a.j.v.ViewResultsFullVisualizer: Add JavaFX to your Java installation if you want to use renderer: org.apache.jmeter.visualizers.RenderInBrowser
2022-09-13 17:41:11,574 INFO o.a.j.s.FileServer: Set new base='/Users/bing/SynologyDrive/HITRUST_DEV/tools/apache-jmeter-5.5'
2022-09-13 17:41:16,085 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2022-09-13 17:41:16,086 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2022-09-13 17:41:16,086 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2022-09-13 17:41:16,088 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2022-09-13 17:41:16,088 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2022-09-13 17:41:16,140 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2022-09-13 17:41:16,194 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2022-09-13 17:41:16,194 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2022-09-13 17:41:16,194 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2022-09-13 17:41:16,195 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-09-13 17:41:16,197 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2022-09-13 17:41:16,198 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2022-09-13 17:41:16,199 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2022-09-13 17:41:16,203 ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime
java.lang.Throwable: Invalid call sequence
	at org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1107) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1145) ~[ApacheJMeter_core.jar:5.5]
	at vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:112) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:79) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2022-09-13 17:41:16,209 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GRPC Request'.
java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Exception.getCause()" is null
	at vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:114) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:79) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
