### ISSUE TITLE
New version 1.2.5 not detected by jMeter

### ISSUE THREAD

**Issue by leanalcabasa** [zalopay-oss/jmeter-grpc-request#186]
Hello,

Thank you for updating the support for protos with no package names.

However, the latest version doesn't seem to be auto-detected by jMeter. I download it and place jmeter-grpc-request.jar in /lib/ext but when I try to add a Sample, gRPC request is not shown.

If I install through plugin manager, v1.2.1 works.

My jMeter version is 5.5.

Can please add v1.2.5 to jMeter Plugins? Or how to add it manually / correctly?

Thank you

**Comment by minhhoangvn** [comment]
Hi @anhldbk, I think your PR #164 and #165 break our plugin

**Comment by minhhoangvn** [comment]
@leanalcabasa, you can work around this by adding the library https://mvnrepository.com/artifact/kg.apc/jmeter-plugins-cmn-jmeter/0.7 into /lib/ext folder 

@anhldbk, the breaking issue is not related to #164 and #165

**Comment by leanalcabasa** [comment]
Thanks @minhhoangvn 

I was able to see the gRPC request, but when I do the actual request itself, it gives me these errors:

2022-10-17 10:36:06,548 WARN v.z.b.c.g.ChannelFactory: Error in create SslContext with NPN_AND_ALPN JDK provider does not support NPN_AND_ALPN protocol
2022-10-17 10:36:06,556 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'TenantConfig Test'.
java.lang.NullPointerException: null
	at org.apache.jmeter.samplers.SampleResult.setResponseData(SampleResult.java:778) ~[ApacheJMeter_core.jar:5.5]
	at vn.zalopay.benchmark.GRPCSampler.generateStatusRuntimeExceptionResponseData(GRPCSampler.java:190) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.generateErrorResult(GRPCSampler.java:175) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.processGrpcRequestSampler(GRPCSampler.java:157) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:95) ~[jmeter-grpc-request.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]

For context, we are exposing grpc through ingress from our kubernetes cluster. This was working previously, but it needed the package name.

**Comment by minhhoangvn** [comment]
Did you try the options disable TLS verify?

**Comment by leanalcabasa** [comment]
Yes,

![image](https://user-images.githubusercontent.com/20421932/196092911-3e4d7e40-de09-41d8-bc0c-5f24a1e39a59.png)

**Comment by leanalcabasa** [comment]
Hello, any potential update for the build fix?

**Comment by kaaviyameena** [comment]
facing same issue do have any solution regarding this?

> Hello, any potential update for the build fix?

**Comment by leanalcabasa** [comment]
I saw they added a new release few days back, and this works for us:

https://github.com/zalopay-oss/jmeter-grpc-request/releases

**Comment by kaaviyameena** [comment]
https://github.com/zalopay-oss/jmeter-grpc-request/compare/v1.2.5...v1.2.5.1 using the latest version of jar

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
