### ISSUE TITLE
GRPC Request 

### ISSUE THREAD

**Issue by Karthicsrv** [zalopay-oss/jmeter-grpc-request#2]
Hi Team,

Currently we are using the Jmeter-GRPC-request sampler for the gRPC services. but we are not able to perform getting below errors, pls provide your support to overcome this issue.

java.lang.RuntimeException: Caught exception while waiting for rpc
	at vn.zalopay.benchmark.core.ClientCaller.call(ClientCaller.java:77) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.sample(GrpcRequest.java:42) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.grpc.DynamicGrpcClient.blockingUnaryCall(DynamicGrpcClient.java:29) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.call(ClientCaller.java:75) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	... 6 more
Caused by: io.netty.channel.ChannelPipelineException: io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:625) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:573) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:516) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.fireProtocolNegotiationEvent(ProtocolNegotiators.java:949) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$WaitUntilActiveHandler.channelActive(ProtocolNegotiators.java:858) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1409) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:307) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	... 1 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider
	at io.netty.handler.ssl.JettyAlpnSslEngine.newClientEngine(JettyAlpnSslEngine.java:55) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:142) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:360) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:335) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.handlerAdded0(ProtocolNegotiators.java:341) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.handlerAdded(ProtocolNegotiators.java:908) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:573) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:516) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.fireProtocolNegotiationEvent(ProtocolNegotiators.java:949) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$WaitUntilActiveHandler.channelActive(ProtocolNegotiators.java:858) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1409) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:307) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	... 1 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
	at io.netty.handler.ssl.JettyAlpnSslEngine.newClientEngine(JettyAlpnSslEngine.java:55) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:142) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:360) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:335) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.handlerAdded0(ProtocolNegotiators.java:341) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.handlerAdded(ProtocolNegotiators.java:908) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:573) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:516) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.fireProtocolNegotiationEvent(ProtocolNegotiators.java:949) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.netty.ProtocolNegotiators$WaitUntilActiveHandler.channelActive(ProtocolNegotiators.java:858) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1409) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:307) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	... 1 more
2020-07-23 16:28:19,622 INFO o.a.j.t.JMeterThread: Thread is done: SingleUser 1-1
2020-07-23 16:28:19,622 INFO o.a.j.t.JMeterThread: Thread finished: SingleUser 1-1
2020-07-23 16:28:19,623 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-07-23 16:28:19,623 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by huynhminhtan** [comment]
Hi @Karthicsrv,

Please tell me the details of the proto file and the JMX file you are using.
Thank you.

**Comment by Karthicsrv** [comment]
Thanks we achieved, but want to know how to handle the grpc --insecure calls.

**Comment by huynhminhtan** [comment]
If you want to execute load test to the server without encryption/authentication, you can set the property `TLS = False`. 

![image](https://user-images.githubusercontent.com/15891411/88831337-63398f80-d1f9-11ea-8351-b547e037347e.png)

Regards.

**Comment by Karthicsrv** [comment]
Thanks,

How to send the Request Metadata values along with the gRPC Request.

**Comment by huynhminhtan** [comment]
Hi @Karthicsrv,

Please check out the [binlib](https://github.com/zalopay-oss/jmeter-grpc-request/tree/binlib) branch to make requests with metadata. I am preparing to merge to master.

To use:
	- Download JMeter at [apache-jmeter-5.1.1.zip](https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.1.1.zip), unzip and then copy [jmeter-grpc-request-1.1.0-SNAPSHOT.jar](https://github.com/zalopay-oss/jmeter-grpc-request/blob/binlib/dist/bin/jmeter-grpc-request-1.1.0-SNAPSHOT.jar) to the `lib/ext` directory of JMeter and restart JMeter.
	- You can see an example at [SegmentService_checkSeg_metadata.jmx](https://github.com/zalopay-oss/jmeter-grpc-request/blob/binlib/dist/benchmark/SegmentService_checkSeg_metadata.jmx). The structure of metadata is `key1:value1,key2:value2`.

The screenshot, with METADATA:

![image](https://user-images.githubusercontent.com/15891411/89000511-c6264600-d321-11ea-8240-be556dc472d6.png)

If you have any questions please don't hesitate to contact me.
Regards.

**Comment by Karthicsrv** [comment]
Thanks for the update - implemented with this jar but getting below error frequently not able to proceed.
Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Invalid token specified rpc error: code = Unauthenticated desc = Invalid authentication scheme used
using the below way 
**authorization:bearer access_token(long length string)** pls let me  know for any changes in the Metadata

**Comment by Karthicsrv** [comment]
Thanks for the update
