### ISSUE TITLE
Import in Proto. ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime

### ISSUE THREAD

**Issue by KarMa230191** [zalopay-oss/jmeter-grpc-request#209]
Proto root directory: C:\Users\***\Desktop\LOAD-382\card-proto
Library directory: C:\Users\***\Desktop\LOAD-382\card-proto\googleapis-master

**Main proto file:**
syntax = "proto3";

package card_proto;

import "validate/validate.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";

option java_multiple_files = true;
option go_package = "./card_proto";
......

**validate.proto** (
<img width="304" alt="image" src="https://user-images.githubusercontent.com/119939601/206376705-d601096d-377e-4bd0-964d-feea70581fc6.png">):
syntax = "proto2";
package validate;

option go_package = "github.com/envoyproxy/protoc-gen-validate/validate";
option java_package = "io.envoyproxy.pgv.validate";

import "google/protobuf/descriptor.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
.......

**i put the google/protobuf folder in googleapis-master folder**.

Debug log:
.....
2022-12-08 09:29:50,647 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2022-12-08 09:29:50,647 DEBUG v.z.b.GRPCSampler: Thread Group 1-1@5fa5f1-GRPCRQ1	testStarted
2022-12-08 09:29:50,647 DEBUG o.a.j.c.GenericController: Calling next on: class org.apache.jmeter.control.GenericController
2022-12-08 09:29:51,647 WARN v.z.b.c.p.ProtocInvoker: Protoc invocation failed with status: 1
2022-12-08 09:29:51,647 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: protoc version: 3.11.4, detected platform: windows-x86_64 (windows server 2012 r2/amd64)

2022-12-08 09:29:51,647 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: embedded: bin/3.11.4/protoc-3.11.4-windows-x86_64.exe

2022-12-08 09:29:51,647 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: executing: [C:\Users\NKHAKI~1\AppData\Local\Temp\2\protocjar5669194425103408726\bin\protoc.exe, @C:\Users\NKHAKI~1\AppData\Local\Temp\2\protoc8579387386937249382.tmp, -IC:\Users\nkhakimov\Desktop\LOAD-382\card-proto\googleapis-master, -IC:\Users\NKHAKI~1\AppData\Local\Temp\2\polyglot-well-known-types5927454401494641017, -IC:\Users\nkhakimov\Desktop\LOAD-382\card-proto, --descriptor_set_out=C:\Users\NKHAKI~1\AppData\Local\Temp\2\descriptor7742103097977242623.pb.bin, --include_imports]

2022-12-08 09:29:51,647 ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime
java.lang.Throwable: Invalid call sequence
	at org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1107) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1145) ~[ApacheJMeter_core.jar:5.5]
	at vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:112) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:79) ~[jmeter-grpc-request-v1.2.1.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_202]
2022-12-08 09:29:51,647 DEBUG o.a.j.c.GenericController: Calling next on: class org.apache.jmeter.control.GenericController
2022-12-08 09:29:51,647 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 took SampleResult: , isFinal: false
2022-12-08 09:29:51,647 DEBUG o.a.j.c.GenericController: Calling next on: class org.apache.jmeter.control.GenericController
2022-12-08 09:29:51,647 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 polling from queue: 0
2022-12-08 09:29:51,647 DEBUG o.a.j.c.GenericController: Calling next on: class org.apache.jmeter.control.GenericController
2022-12-08 09:29:51,647 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 took from queue: null, isFinal: false
2022-12-08 09:29:51,647 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2022-12-08 09:29:51,647 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 exiting with FINAL EVENT: false, null: true
2022-12-08 09:29:51,647 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2022-12-08 09:29:51,647 DEBUG v.z.b.GRPCSampler: Thread Group 1-1@5fa5f1-GRPCRQ1	testEnded
2022-12-08 09:29:51,647 DEBUG o.a.j.t.ThreadGroup: Ending thread Thread Group 1-1
2022-12-08 09:29:51,647 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2022-12-08 09:29:51,647 DEBUG o.a.j.v.b.BackendListener: testEnded called on instance Backend Listener#1
2022-12-08 09:29:51,663 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 taking SampleResult from queue: 1
2022-12-08 09:29:51,663 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 took SampleResult: , isFinal: true
2022-12-08 09:29:51,663 DEBUG o.a.j.v.b.BackendListener: Thread: Thread-559 exiting with FINAL EVENT: true, null: false
2022-12-08 09:29:51,663 INFO o.a.j.v.b.BackendListener: Worker ended
...

why am i getting this error?? ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime
Please, help...!

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
