### ISSUE TITLE
Package version not available in Package Manger GUI, throws uncaught exception

### ISSUE THREAD

**Issue by steverawlins-zebra** [zalopay-oss/jmeter-grpc-request#242]
as seen in the jmeter log:

```
    2023-03-30 11:59:06,746 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalArgumentException: Version grpc-request not found for plugin jmeter-grpc-request
        at org.jmeterplugins.repository.Plugin.getDownloadUrl(Plugin.java:286) ~[jmeter-plugins-manager-1.8.jar:?]
        at org.jmeterplugins.repository.PluginsList.getMavenInfo(PluginsList.java:227) ~[jmeter-plugins-manager-1.8.jar:?]
        at org.jmeterplugins.repository.PluginsList.getDescriptionHTML(PluginsList.java:204) ~[jmeter-plugins-manager-1.8.jar:?]
        at org.jmeterplugins.repository.PluginsList.valueChanged(PluginsList.java:146) ~[jmeter-plugins-manager-1.8.jar:?]
        at javax.swing.JList.fireSelectionValueChanged(JList.java:1831) ~[?:?]
        at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1845) ~[?:?]
        at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224) ~[?:?]
        at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:191) ~[?:?]
        at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:728) ~[?:?]
        at javax.swing.JList.setValueIsAdjusting(JList.java:2179) ~[?:?]
        at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(BasicListUI.java:2988) ~[?:?]
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298) ~[?:?]
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
        at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
        at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
        at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:5001) ~
        at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]

```

Uncaught Exception java.lang.IllegalArgumentException: Version grpc-request not found for plugin jmeter-grpc-request in thread Thread[AWT-EventQueue-0,6,main]. See log file for details.

<img width="1156" alt="grpcpackagedoc1showlist" src="https://user-images.githubusercontent.com/52328771/228911627-6e9222e8-4b2c-48d5-9f8b-3e9ff5c90e53.png">
<img width="1163" alt="grpcpackagedoc2afterselect" src="https://user-images.githubusercontent.com/52328771/228911631-4ecdac81-fcbf-47bc-8982-3a213ba2fafa.png">

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
