### ISSUE TITLE
Issues with threads with deadlined messages

### ISSUE THREAD

**Issue by pmirek** [zalopay-oss/jmeter-grpc-request#243]
Looks like there is still problem seen when deadline is hit, even when channel settings are in scenario:

Warning when threads start (which is possibly acceptable and not related to the problem):

    WARN v.z.b.c.g.ChannelFactory: Error in create SslContext with NPN_AND_ALPN JDK provider does not support NPN_AND_ALPN protocol

Then deadlined message happens, which is seen in logs like:

    ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'smoke-test'.
    java.lang.NullPointerException: null
       at org.apache.jmeter.samplers.SampleResult.setResponseData(SampleResult.java:778) ~[ApacheJMeter_core.jar:5.5]
       at vn.zalopay.benchmark.GRPCSampler.generateStatusRuntimeExceptionResponseData(GRPCSampler.java:190) ~[jmeter-grpc-request.jar:?]
       at vn.zalopay.benchmark.GRPCSampler.generateErrorResult(GRPCSampler.java:175) ~[jmeter-grpc-request.jar:?]
       at vn.zalopay.benchmark.GRPCSampler.processGrpcRequestSampler(GRPCSampler.java:157) ~[jmeter-grpc-request.jar:?]
       at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:95) ~[jmeter-grpc-request.jar:?]
       at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
       at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
       at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
       at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
       at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]

Thread is running, and causing multiple errors, below is example with json assertion failing all the time because of this:

    1680586225770,0,smoke-test, 500, 14 UNAVAILABLE,SUBSCRIBER/FOO Tests 1-1,text,false,Expected to find an object with property ['status'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.,24,0,5,5,null,0,0,0

Example settings:
![image](https://user-images.githubusercontent.com/21124881/229794080-d854cacc-a7e6-4de2-a3e1-c78321b5cc6d.png)

Error seen in JMeter report :
![image](https://user-images.githubusercontent.com/21124881/229795074-bc6696bf-1bff-4fb4-9b43-888105def352.png)

Screenshot with increasing errored message throughput because of the issue - each step is caused by another thread affected by deadlined message:
![image](https://user-images.githubusercontent.com/21124881/229798434-ac0b350d-4318-4191-8a80-a70a96faf0c4.png)

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by pmirek** [comment]
Any plans on fixing this? This is show stopper in case of communication errors, as it stops whole traffic (thread by thread until all are unresponsive) instead of re-try and running the traffic again after.

**Comment by philippmoritzer** [comment]
Same problem,  did you get around to fix this?

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by pmirek** [comment]
the issue is still there, any plans for fixes?
