### ISSUE TITLE
"Exception: Could not extract package name" for proto without package

### ISSUE THREAD

**Issue by walbertus** [zalopay-oss/jmeter-grpc-request#27]
Got `Exception: Could not extract package name` while running this plugin for proto without `package`

`package` should be optional for proto file ([reference](https://developers.google.com/protocol-buffers/docs/proto3#packages))

Error line: https://github.com/zalopay-oss/jmeter-grpc-request/blob/master/src/main/java/vn/zalopay/benchmark/core/protobuf/ProtoMethodName.java#L28

```
2021-02-18 16:17:10,180 ERROR o.a.j.t.JMeterThread: Error calling threadStarted
java.lang.IllegalArgumentException: Could not extract package name from <redacted>
	at vn.zalopay.benchmark.core.protobuf.ProtoMethodName.parseFullGrpcMethodName(ProtoMethodName.java:31) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:38) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:32) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.init(GRPCSampler.java:62) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.threadStarted(GRPCSampler.java:105) ~[jmeter-grpc-request-1.1.2.jar:?]
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:784) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:993) [jorphan.jar:5.4.1]
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:976) [jorphan.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:752) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:740) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:252) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by walbertus** [comment]
The package is used [here](https://github.com/zalopay-oss/jmeter-grpc-request/blob/394d461b8108231b58d06281cf0ff029e6a7153b/src/main/java/vn/zalopay/benchmark/core/protobuf/ServiceResolver.java#L85) to optimize the search

**Comment by arnidhi** [comment]
Do we have any solution to ignore package name?

**Comment by marmotkaa** [comment]
Hi!
I have the same problem, could you help with it ?

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
