### ISSUE TITLE
Parsing request error

### ISSUE THREAD

**Issue by ammarar** [zalopay-oss/jmeter-grpc-request#280]
I am trying to use the jmeter-grpc-request plugin with our proto files and services. However, when I run it I get the following stacktrace:
```
java.lang.RuntimeException: Caught exception while parsing request for rpc
	at vn.zalopay.benchmark.core.ClientCaller.buildRequestAndMetadata(ClientCaller.java:187)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcInCurrentThread(GRPCSampler.java:204)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcRequestSampler(GRPCSampler.java:133)
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:90)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
	at java.lang.Thread.run(Thread.java:829)
```
Is there a way to understand what was the problem that caused this to happen? The request JSON I provided is the autogenerated one.

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by CosTeiiRa** [comment]
I'm getting the same error in JMeter (5.6.2).
The proto I'm using is this one from [seldon](https://github.com/SeldonIO/seldon-core/blob/v2.6.0/apis/mlops/v2_dataplane/v2_dataplane.proto), any method I'm trying to use the response is precisely that one.

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
