### ISSUE TITLE
import googleapis problem

### ISSUE THREAD

**Issue by SemihSaydamAndroid** [zalopay-oss/jmeter-grpc-request#281]
Hello,

Hi, we are encountering an error when using jmeter-grpc-request. In the proto file, if we import from googleapis, we get a "file not found" error.

```
protoc execute error: 
	google/type/money.proto: File not found.
	service.proto:3:1: Import "google/type/money.proto" was not found or had errors.

	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.protocInvokerErrorHandler(ProtocInvoker.java:329) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:214) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:97) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:47) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	... 39 more
2023-08-28 16:38:30,716 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.RuntimeException: Unable to resolve service by invoking protoc
	at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:55) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.getProtoMethods(GRPCSamplerGui.java:353) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.reloadProtoMethods(GRPCSamplerGui.java:343) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.lambda$registerListGRPCMethods$0(GRPCSamplerGui.java:498) ~[jmeter-grpc-request-1.2.5.1.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at com.github.weisj.darklaf.ui.button.DarkButtonListener.mouseReleased(DarkButtonListener.java:72) ~[darklaf-core-2.5.4.jar:2.5.4]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: vn.zalopay.benchmark.exception.ProtocInvocationException: 
Protoc error exit code: 1
```
We were able to overcome this error with a work around. But we wanted to know if there is a more permanent method for this.

```
syntax = "proto3";

import "google/type/money.proto";

message HelloWorldBusinessGrpcRequest {
  string name = 1;
}
...
```

I get the error I gave above in a proto import such as. To fix this, I find money.proto, **manually add it to the folder, and change the import** to:

`import "money.proto"`

I also get the content from : https://github.com/googleapis/googleapis/blob/master/google/type/money.proto

In this case, it starts working, but we have to add a manual proto for every import used. Can you help solve this?

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
