### ISSUE TITLE
enable TLS but don't work

### ISSUE THREAD

**Issue by fault-segment** [zalopay-oss/jmeter-grpc-request#285]
2023-10-16 16:53:43,889 ERROR v.z.b.GRPCSampler: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createSslContext(ChannelFactory.java:70)
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createSSLMessageChannel(ChannelFactory.java:64)
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:55)
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannel(ChannelFactory.java:39)
	at vn.zalopay.benchmark.core.ClientCaller.createDynamicClient(ClientCaller.java:154)
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:96)
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:53)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcClient(GRPCSampler.java:81)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcInCurrentThread(GRPCSampler.java:203)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcRequestSampler(GRPCSampler.java:133)
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:90)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
	at java.lang.Thread.run(Thread.java:748)

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
