### ISSUE TITLE
protoc execution error

### ISSUE THREAD

**Issue by khteh** [zalopay-oss/jmeter-grpc-request#286]
![image](https://github.com/zalopay-oss/jmeter-grpc-request/assets/3871483/154d0333-7a3c-428f-bd0d-61cdc15e06f7)

```
java.lang.RuntimeException: Unable to resolve service by invoking protoc: 

Protoc error exit code: 1

Protoc execute command: 
	protoc-jar: protoc version: 3.21.4, detected platform: linux-x86_64 (linux/amd64)
	protoc-jar: embedded: bin/3.21.4/protoc-3.21.4-linux-x86_64.exe
	protoc-jar: executing: [/tmp/protocjar4374176718459922555/bin/protoc.exe, /home/workspace/JMeter/proto/request.proto, /home/workspace/JMeter/proto/search.proto, /home/workspace/JMeter/proto/identity.proto, /home/workspace/JMeter/proto/quotation.proto, /home/workspace/JMeter/proto/buyer.proto, /home/workspace/JMeter/proto/industry.proto, /home/workspace/JMeter/proto/shop.proto, /home/workspace/JMeter/proto/invoice.proto, /home/workspace/JMeter/proto/file.proto, /home/workspace/JMeter/proto/order.proto, /home/workspace/JMeter/proto/stringInputParam.proto, /home/workspace/JMeter/proto/seller.proto, /home/workspace/JMeter/proto/document.proto, /home/workspace/JMeter/proto/numberRange.proto, /home/workspace/JMeter/proto/cartitem.proto, /home/workspace/JMeter/proto/notification.proto, /home/workspace/JMeter/proto/tender.proto, /home/workspace/JMeter/proto/media.proto, /home/workspace/JMeter/proto/dateRange.proto, /home/workspace/JMeter/proto/response.proto, /home/workspace/JMeter/proto/institution.proto, /home/workspace/JMeter/proto/status.proto, /home/workspace/JMeter/proto/s3.proto, /home/workspace/JMeter/proto/subscription.proto, /home/workspace/JMeter/proto/address.proto, /home/workspace/JMeter/proto/punchin.proto, /home/workspace/JMeter/proto/rfq.proto, /home/workspace/JMeter/proto/productFilter.proto, /home/workspace/JMeter/proto/brand.proto, /home/workspace/JMeter/proto/stripe.proto, /home/workspace/JMeter/proto/bid.proto, /home/workspace/JMeter/proto/chat.proto, /home/workspace/JMeter/proto/voucher.proto, /home/workspace/JMeter/proto/user.proto, /home/workspace/JMeter/proto/category.proto, /home/workspace/JMeter/proto/aribacartitem.proto, /home/workspace/JMeter/proto/product.proto, /home/workspace/JMeter/proto/dhl.proto, -I/home/workspace/JMeter, -I/tmp/polyglot-well-known-types13462492735064439303, -I/home/workspace/JMeter/proto, --descriptor_set_out=/tmp/descriptor9459734690719246173.pb.bin, --include_imports]

Protoc execute error: 
	request.proto:6:11: "MyRequest.PageRequest.page" is already defined in file "proto/request.proto".
	request.proto:7:11: "MyRequest.PageRequest.pageSize" is already defined in file "proto/request.proto".
	request.proto:5:9: "MyRequest.PageRequest" is already defined in file "proto/request.proto".
	product.proto:7:1: Import "request.proto" was not found or had errors.
	product.proto:21:5: "MyRequest.PageRequest" seems to be defined in "proto/request.proto", which is not imported by "product.proto".  To use it here, please add the necessary import.
	proto/search.proto:5:1: Import "request.proto" was not found or had errors.
	proto/search.proto:7:1: Import "product.proto" was not found or had errors.
	proto/search.proto:14:5: "MyRequest.PageRequest" seems to be defined in "proto/request.proto", which is not imported by "proto/search.proto".  To use it here, please add the necessary import.
	proto/search.proto:22:14: "ProductSummary" is not defined.

	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:88)
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:53)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcClient(GRPCSampler.java:81)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcInCurrentThread(GRPCSampler.java:203)
	at vn.zalopay.benchmark.GRPCSampler.initGrpcRequestSampler(GRPCSampler.java:133)
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:90)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
