### ISSUE TITLE
NoSuchMethodError: com.google.common.net.HostAndPort.getHost()

### ISSUE THREAD

**Issue by mustafa-qamaruddin** [zalopay-oss/jmeter-grpc-request#289]
I have tried version  (5.6.2) and installed the plugin through the plugin manager. Then I added a simple proto to test and I get this error:

<pre>
2023-11-01 16:00:16,726 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[Thread-Gruppe 1-1,6,main]
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHost()Ljava/lang/String;
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:51) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannel(ChannelFactory.java:39) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.createDynamicClient(ClientCaller.java:154) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:96) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:53) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.initGrpcClient(GRPCSampler.java:81) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.initGrpcInCurrentThread(GRPCSampler.java:203) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.initGrpcRequestSampler(GRPCSampler.java:133) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:90) ~[jmeter-grpc-request.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.6.2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_391]
2023-11-01 16:00:16,727 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2023-11-01 16:00:16,727 INFO v.z.b.GRPCSampler: testEnded
2023-11-01 16:00:16,733 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
</pre>

I have also downloaded the released jar v1.2.6 and it gives the same error.

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
