### ISSUE TITLE
Method unimplemented

### ISSUE THREAD

**Issue by niklascube** [zalopay-oss/jmeter-grpc-request#3]
When trying to call the rpc stub following error occurs: 
```
2020-07-28 14:44:51,247 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GrpcRequest'.
java.lang.RuntimeException: Caught exception while waiting for rpc
	at vn.zalopay.benchmark.core.ClientCaller.call(ClientCaller.java:77) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.sample(GrpcRequest.java:42) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method PACKAGE.SERVICE/METHOD-ONE is unimplemented
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.grpc.DynamicGrpcClient.blockingUnaryCall(DynamicGrpcClient.java:29) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.call(ClientCaller.java:75) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	... 6 more
```

However, the call is recognized by the grpc server:

```
PACKAGE.SERVICE/METHOD-ONE
2020-07-28 14:44:51.227  INFO 975 --- [ault-executor-0] o.l.springboot.grpc.ais.LogInterceptor   : PACKAGE.SERVICE/METHOD-ONE
```

My proto looks like this:

```
package PACKAGE;

service SERVICE {
  rpc METHOD-ONE(Request-one) returns (Response-one) {}
  rpc METHOD-TWO(Request-two) returns (Response-two) {}
}
```

Here also my JMX:

```
<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">1</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">1</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </ThreadGroup>
      <hashTree>
        <vn.zalopay.benchmark.testbean.GrpcRequest guiclass="TestBeanGUI" testclass="vn.zalopay.benchmark.testbean.GrpcRequest" testname="GrpcRequest" enabled="true">
          <longProp name="DEADLINE">100000</longProp>
          <stringProp name="FULL_METHOD">PACKAGE.SERVICE/METHOD-ONE</stringProp>
          <stringProp name="HOST_PORT">localhost:6565</stringProp>
          <stringProp name="PROTO_FOLDER">/Users/me/Development/BA/project/src/main/proto</stringProp>
          <stringProp name="REQUEST_FILE">/Users/me/Development/BA/project-requests/Request-one.json</stringProp>
          <boolProp name="TLS">false</boolProp>
          <stringProp name="REQUEST_JSON"></stringProp>
        </vn.zalopay.benchmark.testbean.GrpcRequest>
        <hashTree/>
        <ResultCollector guiclass="ViewResultsFullVisualizer" testclass="ResultCollector" testname="View Results Tree" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp>
            <name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <sentBytes>true</sentBytes>
              <url>true</url>
              <threadCounts>true</threadCounts>
              <idleTime>true</idleTime>
              <connectTime>true</connectTime>
            </value>
          </objProp>
          <stringProp name="filename"></stringProp>
        </ResultCollector>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>

```

In the end, I do not understand how the method is not recognized.
Do you have an idea, why ?
I'm very thankful for every help!

**Comment by huynhminhtan** [comment]
I see that you have the correct structure of FULL_METHOD (method = PACKAGE.SERVICE / METHOD-ONE), but it seems that you have removed the details of the proto file, this is very difficult for me to find the problem correctly. Maybe the proto file uses external packages like Google APIs (you're using google / rpc / status.proto, google / protobuf / field_mask.proto, ...). Unfortunately, JMeter-GRPC-Request does not support it yet. (please checkout the [binlib](https://github.com/zalopay-oss/jmeter-grpc-request/tree/binlib) branch for details)

Besides, I also see the error message `Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method PACKAGE.SERVICE / METHOD-ONE is unimplemented`, make sure METHOD-ONE method has been correctly defined on the server. To make sure your GRPC-server is working properly, you can call some requests using the GRPC client tool / client command line as BloomRPC, etc.

Please check the above, to solve your problem quickly please send me details of proto file and JSON request file if possible.

Welcome and Thank you.

**Comment by niklascube** [comment]
So, the method implementation is just fined according to BloomRPC, the service works without problems.

My whole proto file looks like this (I still anonymised something but it shouldn't effect something due it does not depend on external packages.

```
syntax = "proto3";

option java_package = "io.grpc.ais";
package ais;

message MessageRequest {
  string token = 1;
}

message MessageResponse {
  string status = 1;
  string error = 2;
  double computing_time = 3;
  int32 totalItems = 4;
  string limit = 5;
}

service banking {
  rpc receiveMessage(MessageRequest) returns (MessageResponse) {}
}
```

Here is also my JSON Request:

```
{
    "token":"HERE IS A JSON WEB TOKEN"
}
```

**Comment by niklascube** [comment]
Update: Something is wrong with my "receiveMessage" on server-side.
I could reproduce it now on BloomRPC.
Nevertheless, every other method or service is working now.
Thanks for your help!
