### ISSUE TITLE
Unable to resolve service by invoking protoc

### ISSUE THREAD

**Issue by debayandesarkar** [zalopay-oss/jmeter-grpc-request#35]
Hi,
I am getting the below error with this sampler. Can you please help in troubleshooting this issue?

```
2021-04-25 00:17:38,015 INFO v.z.j.g.c.GrpcClientSampler: Created GrpcClientSampler
2021-04-25 00:17:38,019 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2021-04-25 00:17:38,020 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2021-04-25 00:17:38,022 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2021-04-25 00:17:38,284 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2021-04-25 00:17:38,285 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2021-04-25 00:17:38,285 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2021-04-25 00:17:38,286 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-04-25 00:17:38,287 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2021-04-25 00:17:38,287 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2021-04-25 00:17:38,290 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2021-04-25 00:17:38,291 INFO v.z.b.GRPCSampler: Thread Group 1-1@3895635e-GRPC Request	testStarted
2021-04-25 00:17:39,208 WARN v.z.b.c.p.ProtocInvoker: Protoc invocation failed with status: 1
2021-04-25 00:17:39,209 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: protoc version: 3.10.1, detected platform: osx-x86_64 (mac os x/x86_64)
2021-04-25 00:17:39,209 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: embedded: bin/3.10.1/protoc-3.10.1-osx-x86_64.exe
2021-04-25 00:17:39,209 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: executing: [/var/folders/4v/ht8prz9n0wl7wv6dvjp2s968lf392v/T/protocjar10133609867773508138/bin/protoc.exe, /opt/GitHub/pay-integrator-api/src/main/proto/com/expedia/payment/integrator/service/v1/integrator_payment_api.proto, -I/opt/GitHub/googleapis-master, -I/var/folders/4v/ht8prz9n0wl7wv6dvjp2s968lf392v/T/polyglot-well-known-types2172559459053989569, -I/opt/GitHub/pay-integrator-api/src/main/proto/com/expedia/payment/integrator/service/v1, --descriptor_set_out=/var/folders/4v/ht8prz9n0wl7wv6dvjp2s968lf392v/T/descriptor40288201410774047.pb.bin, --include_imports]
2021-04-25 00:17:39,209 ERROR o.a.j.t.JMeterThread: Error calling threadStarted
java.lang.RuntimeException: Unable to resolve service by invoking protoc
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:54) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:32) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.init(GRPCSampler.java:62) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.threadStarted(GRPCSampler.java:105) ~[jmeter-grpc-request-1.1.2.jar:?]
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:769) [ApacheJMeter_core.jar:5.3]
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:993) [jorphan.jar:5.3]
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:976) [jorphan.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:737) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:725) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:252) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: vn.zalopay.benchmark.core.protobuf.ProtocInvoker$ProtocInvocationException: Got exit code [1] from protoc with args [[/opt/GitHub/pay-integrator-api/src/main/proto/com/expedia/payment/integrator/service/v1/integrator_payment_api.proto, -I/opt/GitHub/googleapis-master, -I/var/folders/4v/ht8prz9n0wl7wv6dvjp2s968lf392v/T/polyglot-well-known-types2172559459053989569, -I/opt/GitHub/pay-integrator-api/src/main/proto/com/expedia/payment/integrator/service/v1, --descriptor_set_out=/var/folders/4v/ht8prz9n0wl7wv6dvjp2s968lf392v/T/descriptor40288201410774047.pb.bin, --include_imports]]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:159) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:104) ~[jmeter-grpc-request-1.1.2.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:52) ~[jmeter-grpc-request-1.1.2.jar:?]
	... 10 more
2021-04-25 00:17:39,210 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GRPC Request'.
java.lang.NullPointerException: null
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:70) ~[jmeter-grpc-request-1.1.2.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-04-25 00:17:39,211 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2021-04-25 00:17:39,211 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2021-04-25 00:17:39,212 INFO v.z.b.GRPCSampler: Thread Group 1-1@3895635e-GRPC Request	testEnded
2021-04-25 00:17:39,212 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2021-04-25 00:17:39,212 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

```

Regards
Debayan

**Comment by huynhminhtan** [comment]
Hi @debayandesarkar,

The protoc compiling was failed. Please recheck your input as Proto Root Directory, Library Directory (if you use **externally lib** as googleapis, ...) then clicking the Listing button in order to get existed methods.

Or, you can start with an example [here](https://github.com/zalopay-oss/jmeter-grpc-request/tree/master/dist/example).

Welcome and Thank you.

**Comment by debayandesarkar** [comment]
Hi @huynhminhtan ,
Thanks for your prompt response. The proto root directory seems to be correct as it found the /opt/GitHub/pay-integrator-api/src/main/proto/com/expedia/payment/integrator/service/v1/integrator_payment_api.proto file. We are not using external library like googleapis. Hence, clicking on the "Listening" button is not rendering any methods. The proto file integrator_payment_api.proto
![Uploading Screen Shot 2021-04-25 at 12.50.07 AM.png…]()
 I am using doesn't have a service name and method name like the example below. Is that the reason the compilation is failing?

service **Bookstore** {
  // Returns a list of all shelves in the bookstore.
  rpc **ListShelves** (google.protobuf.Empty) returns (ListShelvesResponse) {
    // Define HTTP mapping.
    // Client example (Assuming your service is hosted at the given 'DOMAIN_NAME'):
    //   curl http://DOMAIN_NAME/v1/shelves
    option (google.api.http) = { get: "/v1/shelves" };
  }

Regards
Debayan

**Comment by huynhminhtan** [comment]
Hi @debayandesarkar,

Do you import other internal proto files? please check file path when importing. The integrator_payment_api.proto doesn't have a **service name** and **method name**, so I wonder how do you make many requests to your gRPC server?

Can you upload portable/simple version of the proto file?

Regards

**Comment by debayandesarkar** [comment]
@huynhminhtan  Did you get a chance to look at my response above? Does these implementation require the service and method names declaration in the .proto file?

Regards
Debayan

**Comment by debayandesarkar** [comment]
@huynhminhtan Thanks for your response.I added the service name and method name in the service .proto file as shown below and the compilation seems to be successful. However, I am getting the below error now.

```
option java_outer_classname = "BraintreeClientImplGrpc";
/* Added to test with JMeter GRPC Request Sampler */
service BraintreeClientImpl {
rpc authorize (AuthorizeRequest) returns (AuthorizeResponse) {}
}
```
Thread Name:Thread Group 1-1
Sample Start:2021-04-28 00:33:07 PDT
Load time:59
Connect Time:0
Latency:0
Size in bytes:38
Sent bytes:0
Headers size in bytes:0
Body size in bytes:38
Sample Count:1
Error Count:1
Data type ("text"|"bin"|""):text
Response code:500
**Response message:Exception: UNAVAILABLE: Network closed for unknown reason**
SampleResult fields:
ContentType: 
DataEncoding: null

Response Data: Caught exception while waiting for rpc

**Comment by debayandesarkar** [comment]
@huynhminhtan Hi, did you get a chance to look at my latest response?

Regards
Debayan

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
