### ISSUE TITLE
Full method not see my methods in proto files

### ISSUE THREAD

**Issue by Xackuuu** [zalopay-oss/jmeter-grpc-request#51]
Good day!
Loaded the grpc plugin and loaded proto files in the "Proto Rot Directories" field, but the full method does not find the methods that are in the proto files. What am I doing wrong??? help me please

**Comment by minhhoangvn** [comment]
Could you please attach any log in JMeter to provide more information about this issue

**Comment by Xackuuu** [comment]
2021-07-05 10:41:48,501 WARN v.z.b.c.p.ProtocInvoker: Protoc invocation failed with status: 1
2021-07-05 10:41:48,501 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: protoc version: 3.10.1, detected platform: windows-x86_64 (windows 10/amd64)

2021-07-05 10:41:48,501 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: embedded: bin/3.10.1/protoc-3.10.1-windows-x86_64.exe

2021-07-05 10:41:48,501 WARN v.z.b.c.p.ProtocInvoker: [Protoc log] protoc-jar: executing: [C:\Users\*\AppData\Local\Temp\protocjar74983695931690834\bin\protoc.exe, C:\Users\*\Desktop\proto\proto2\openapi.proto, C:\Users\*\Desktop\proto\proto2\at-api-front.proto, -IC:\apache-jmeter-5.2.1\bin, -IC:\Users\*\AppData\Local\Temp\polyglot-well-known-types6581173088312506459, -IC:\Users\*\Desktop\proto\proto2, --descriptor_set_out=C:\Users\*\AppData\Local\Temp\descriptor8083492068979646073.pb.bin, --include_imports]

2021-07-05 10:41:48,501 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.RuntimeException: Unable to resolve service by invoking protoc
                at vn.zalopay.benchmark.core.ClientList.listServices(ClientList.java:20) ~[jmeter-grpc-request-1.1.2.jar:?]
                at vn.zalopay.benchmark.GRPCSamplerGui.getMethods(GRPCSamplerGui.java:274) ~[jmeter-grpc-request-1.1.2.jar:?]
                at vn.zalopay.benchmark.GRPCSamplerGui.access$100(GRPCSamplerGui.java:35) ~[jmeter-grpc-request-1.1.2.jar:?]
                at vn.zalopay.benchmark.GRPCSamplerGui$1.actionPerformed(GRPCSamplerGui.java:244) ~[jmeter-grpc-request-1.1.2.jar:?]
                at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_171]
                at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_171]
                at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_171]
                at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_171]
                at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[?:1.8.0_171]
                at java.awt.Component.processMouseEvent(Component.java:6533) ~[?:1.8.0_171]
                at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_171]
                at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_171]
                at java.awt.Container.processEvent(Container.java:2238) ~[?:1.8.0_171]
                at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_171]
                at java.awt.Container.dispatchEventImpl(Container.java:2296) ~[?:1.8.0_171]
                at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_171]
                at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897) ~[?:1.8.0_171]
                at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534) ~[?:1.8.0_171]
                at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475) ~[?:1.8.0_171]
                at java.awt.Container.dispatchEventImpl(Container.java:2282) ~[?:1.8.0_171]
                at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_171]
                at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_171]
                at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) ~[?:1.8.0_171]
                at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_171]
                at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_171]
                at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_171]
                at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_171]
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_171]
                at java.awt.EventQueue$4.run(EventQueue.java:733) ~[?:1.8.0_171]
                at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_171]
                at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_171]
                at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) ~[?:1.8.0_171]
                at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_171]
                at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_171]
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_171]
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_171]
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_171]
                at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_171]
Caused by: vn.zalopay.benchmark.core.protobuf.ProtocInvoker$ProtocInvocationException: Got exit code [1] from protoc with args [[C:\Users\*\Desktop\proto\proto2\openapi.proto, C:\Users\*\Desktop\proto\proto2\at-api-front.proto, -IC:\apache-jmeter-5.2.1\bin, -IC:\Users\*\AppData\Local\Temp\polyglot-well-known-types6581173088312506459, -IC:\Users\*\Desktop\proto\proto2, --descriptor_set_out=C:\Users\*\AppData\Local\Temp\descriptor8083492068979646073.pb.bin, --include_imports]]
                at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:159) ~[jmeter-grpc-request-1.1.2.jar:?]
                at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:104) ~[jmeter-grpc-request-1.1.2.jar:?]
                at vn.zalopay.benchmark.core.ClientList.listServices(ClientList.java:18) ~[jmeter-grpc-request-1.1.2.jar:?]
                ... 39 more


> Could you please attach any log in JMeter to provide more information about this issue

**Comment by zongxiuxuan** [comment]
The same problem，help me please

**Comment by pcdopc** [comment]
+1

**Comment by huynhminhtan** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by huynhminhtan** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
