### ISSUE TITLE
Unable to get plugin to run in JMeter

### ISSUE THREAD

**Issue by vrugore** [zalopay-oss/jmeter-grpc-request#57]
Hi,
I am getting following error when I try to run my GRPC request from JMeter. Can someone please help

ava.util.ServiceConfigurationError: io.grpc.NameResolverProvider: io.grpc.grpclb.SecretGrpclbNameResolverProvider$Provider Unable to get public no-arg constructor
	at java.util.ServiceLoader.fail(ServiceLoader.java:581) ~[?:?]
	at java.util.ServiceLoader.getConstructor(ServiceLoader.java:672) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384) ~[?:?]
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67) ~[jmeter-grpc-request-1.1.1.jar:?]
	at io.grpc.NameResolverRegistry.getDefaultRegistry(NameResolverRegistry.java:101) ~[jmeter-grpc-request-1.1.1.jar:?]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(AbstractManagedChannelImplBuilder.java:99) ~[jmeter-grpc-request-1.1.1.jar:?]
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:128) ~[jmeter-grpc-request-1.1.1.jar:?]
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:123) ~[jmeter-grpc-request-1.1.1.jar:?]
	at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:109) ~[jmeter-grpc-request-1.1.1.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:39) ~[jmeter-grpc-request-1.1.1.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannel(ChannelFactory.j

Regards
Vru

**Comment by huynhminhtan** [comment]
Hi @vrugore,

First, for simplicity, you can run the example here [#running-the-examples](https://github.com/zalopay-oss/jmeter-grpc-request#running-the-examples).
If successful, please make sure you have configured the correct config as described [#configurations](https://github.com/zalopay-oss/jmeter-grpc-request#configurations). Finally, you can get the latest version of JMeter gRPC Request, by checking the master branch then build and try again.

I hope everything will be all right.
Regards

**Comment by vrugore** [comment]
Hi ,
Thanks for your reply.I tried again and am getting same error. Can it be because I have Java 11 installed? I am using Jmeter 5.4.1

**Comment by huynhminhtan** [comment]
Hi @vrugore,
You can use JMeter 5.4.1 & Java 11. Did you run the example successfully before you tried to run your test script JMX?

**Comment by vrugore** [comment]
Hi,
I have reinstalled the JMeter and tried to access the sample. The sample itself is giving me status 500 code. Am i missing any setup configuration required.

**Comment by huynhminhtan** [comment]
Hi @vrugore,

I will close the issue as obsolete. You can reopen the case again should there still be any issues. Please check the latest release and run with the [example](https://github.com/zalopay-oss/jmeter-grpc-request#running-the-examples). Regards.
