### ISSUE TITLE
support of grpc-web

### ISSUE THREAD

**Issue by noahsi-cuigd** [zalopay-oss/jmeter-grpc-request#7]
We are tring the jmeter-grpc-request from localhost to the AWS server, which can only accept grpc-web client.
Can you give me some Suggestions please.
```
2020-09-11 11:12:56,996 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-09-11 11:12:56,996 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-09-11 11:12:56,996 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-09-11 11:12:57,068 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-09-11 11:12:57,068 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-09-11 11:12:57,068 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-09-11 11:12:57,068 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-09-11 11:12:57,068 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-09-11 11:12:57,068 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-09-11 11:12:57,069 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-09-11 11:12:57,345 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GrpcRequest'.
java.lang.RuntimeException: Caught exception while waiting for rpc
	at vn.zalopay.benchmark.core.ClientCaller.call(ClientCaller.java:77) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.testbean.GrpcRequest.sample(GrpcRequest.java:42) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[jmeter-grpc-client-sampler.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[jmeter-grpc-client-sampler.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[jmeter-grpc-client-sampler.jar:?]
	at vn.zalopay.benchmark.core.grpc.DynamicGrpcClient.blockingUnaryCall(DynamicGrpcClient.java:29) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.call(ClientCaller.java:75) ~[jmeter-grpc-request-1.0-SNAPSHOT.jar:?]
	... 6 more
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[jmeter-grpc-client-sampler.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[jmeter-grpc-client-sampler.jar:?]
	... 1 more
2020-09-11 11:12:57,345 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2020-09-11 11:12:57,345 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-09-11 11:12:57,345 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-09-11 11:12:57,345 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

```

**Comment by huynhminhtan** [comment]
Hi @noahsi-cuigd,

You call via domain or IP / port if using the domain please check and select `TLS = true`, 
Please check that your server can serve HTTP2, more https://github.com/grpc/grpc-java/issues/2905
Regards.

**Comment by noahsi-cuigd** [comment]
@huynhminhtan 
Thanks!
Our server don't serve HTTP2 now...
Is there some way to change this plugin's protocol to HTTP1.1 easily?

**Comment by noahsi-cuigd** [comment]
We use jmeter recording instead, thx~
