### ISSUE TITLE
ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime

### ISSUE THREAD

**Issue by jacek-d** [zalopay-oss/jmeter-grpc-request#92]
Using version 1.2.0 I'm getting the following error:
2022-01-03 15:01:50,747 ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime
java.lang.Throwable: Invalid call sequence
	at org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1107) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1145) [ApacheJMeter_core.jar:5.4.2]
	at vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:113) [jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:80) [jmeter-grpc-request.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.2]
	at java.lang.Thread.run(Thread.java:829) [?:?]

When I added a log.error(...) in the GRPCSampler.sample(...):79 I can see this is the root cause:
java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:432) ~[jmeter-grpc-request.jar:?]
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:275) ~[jmeter-grpc-request.jar:?]
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:821) ~[jmeter-grpc-request.jar:?]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:576) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createSslContext(ChannelFactory.java:61) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createSSLMessageChannel(ChannelFactory.java:46) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:40) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.grpc.ChannelFactory.createChannel(ChannelFactory.java:30) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.createDynamicClient(ClientCaller.java:122) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.init(ClientCaller.java:73) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientCaller.<init>(ClientCaller.java:46) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.initGrpcClient(GRPCSampler.java:56) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:65) [jmeter-grpc-request.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.2]
	at java.lang.Thread.run(Thread.java:829) [?:?]

Same test plan was working correctly with the code in PR #84 that I tested.

I have 'SSL/TLS' checkbox on.

**Comment by Andrey-Demidovich** [comment]
I have spotted the same issue. It happens on Linux machine, while it is ok with the same script on Windows.
