### ISSUE TITLE
grpc  ERROR 

### ISSUE THREAD

**Issue by love425429** [zalopay-oss/jmeter-grpc-request#96]
2022-01-12 18:29:50,856 ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime
java.lang.Throwable: Invalid call sequence
	at org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1107) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1145) [ApacheJMeter_core.jar:5.4.3]
	at vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:112) [jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:79) [jmeter-grpc-request.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191

**Comment by love425429** [comment]
i just download the project and  build the grpc request jar
then

**Comment by love425429** [comment]
![image](https://user-images.githubusercontent.com/1023309/149124210-e6e96ddc-a26a-463d-ba6d-d2390ae3cd5e.png)
to  test my grpc server got this error

**Comment by yl-yue** [comment]
> 你好，由于真实的异常信息，添加在响应结果中，你需要查看观察树中的响应信息来排查问题

Hello, because the real exception information is added to the response result, you need to check the response information in the observation tree to troubleshoot the problem

**Comment by cybercyto82** [comment]
I have the same problem. I do not understand to solve it. I need some help!

**Comment by ReadyFish** [comment]
2022-05-26 14:03:32,300 ERROR o.a.j.s.SampleResult: setEndTime must be called after setStartTime
java.lang.Throwable: Invalid call sequence
	at org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1104) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1143) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:112) [jmeter-grpc-request-v1.2.1.jar:?]
	at vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:79) [jmeter-grpc-request-v1.2.1.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

Same issue for me. Any available solution?

**Comment by pubaradi** [comment]
Facing similar issue : 
{"exception":{"exception_class":"java.lang.Throwable","exception_message":"Invalid call sequence","stacktrace":"java.lang.Throwable: Invalid call sequence\n\tat org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1107)\n\tat org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1145)\n\tat vn.zalopay.benchmark.GRPCSampler.errorResult(GRPCSampler.java:112)\n\tat vn.zalopay.benchmark.GRPCSampler.sample(GRPCSampler.java:79)\n\tat org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638)\n\tat org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)\n\tat org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)\n\tat org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"},"@version":1,"source_host":"d04ecf912473","message":"setEndTime must be called after setStartTime","thread_name":"172.17.0.2-Thread Group 1-1"

The request response says "Unable to execute protoc binary"

Not sure if its my issue or grpc sampler issue. Can someone please help here?

**Comment by minhhoangvn** [comment]
Please run your JMeter with debug log enable and provide full log information, this issue happening in the Linux when running the gRPC with the proto file has imported another proto, and both of them has placed in the same directory

**Comment by pubaradi** [comment]
> Please run your JMeter with debug log enable and provide full log information, this issue happening in the Linux when 
[Grpc.zip](https://github.com/zalopay-oss/jmeter-grpc-request/files/9016534/Grpc.zip)
running the gRPC with the proto file has imported another proto, and both of them has placed in the same directory

The proto file is not importing another file. 
The folder has jmx and proto file and other dependency jars in it. Please find attached the zip file with the details.

**Comment by minhhoangvn** [comment]
Did you run the test through GUI or command line?

**Comment by pubaradi** [comment]
It is through command line.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pubaradi** [comment]
Hi,

Thanks for the update. Can you please publish this latest release to plugins repo as well JMeter Plugins :: JMeter-Plugins.org<https://jmeter-plugins.org/>.
Our service picks up the plugins from there. Or if it is an automated process, could please let us know the ETA for the plugin to be published there.

Thanks
Purva

**Comment by pubaradi** [comment]
Even with the latest plugin, I see an error running the protoc binary. Please find attached the logs.

Thanks
Purva

**Comment by minhhoangvn** [comment]
@pubaradi  please provide the log file

**Comment by pubaradi** [comment]
[engine1_worker.log](https://github.com/zalopay-oss/jmeter-grpc-request/files/9045880/engine1_worker.log)

**Comment by minhhoangvn** [comment]
@pubaradi it was empty log file. However, please set the proto path folder in your JMX test plan, when running with command-line it require the proto path folder value

**Comment by pubaradi** [comment]
Attaching it here again. Let me know if this is a known error.

Thanks
Pura

**Comment by minhhoangvn** [comment]
I have reviewed your JMX file and it missing the proto path folder value and it leading to error when invoking the protoc process

**Comment by pubaradi** [comment]
Thanks Minh for your constant help. Since we are calling it from cmd, I am passing a relative path. Does relative path is supported in linux environment cmd.
I am just passing "/" to indicate to check it in the current directory but it still throws the same error.

Thanks
Purva

**Comment by yl-yue** [comment]
Sorry, this is a PR that has been delayed for a long time. Due to testing in offline development, I forgot to submit the PR.

Subsequent exception prompts will appear more friendly and will no longer throw exceptions in exception handling

**Comment by pubaradi** [comment]
PFA the logs zip file.

Thanks
Purva
